### PR TITLE
Restauraunt site

### PR DESCRIPTION
**Pull request by igorkol91**
In this project, I used js to put all tags and CSS classes in index.html. There is only a container.
- There is an index.html and main.js in dist folder that contains does all the work with some backup files
- I have an index.js in the src file and a module folder that contains codes for each header link separately.

### CODE REVIEW

**Review by igorkol91 — COMMENTED** [review]
.

**Review by enaburekhan — COMMENTED** [review]
# Status: Invalid
Hi Igor!
Friendly reminder! 
Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
When done with the update. Kindly use the same PR for code review. Instead of opening a new one. This project will be marked invalid in your dashboard.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Review by oloomoses — CHANGES_REQUESTED** [review]
## Hello @igorkol91,
**You have done a commendable job on this project :muscle: :clap:.**
## Highlights
- Great job on the project file structure :heavy_check_mark: 
- Well done on the pull request :heavy_check_mark: 
- Well done on the linter configuration :muscle:

## To improve
- [x] Kindly add instructions on setting up and running the project locally in the readme. Also, remember to add a project description to make the readme more descriptive
- [ ] The live link provided in the readme is not working. Kindly ensure that the app is deployed and the link provided is working
- [x] Kindly remove the console log statements in the index.js file
- [x] Kindly ensure that the necessary run common commands like `build`, `development` are added in `package.json` inside \`scripts'. Below is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))

```json
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack server --mode development --open" // optional
  },
```
- [x] For the start command to execute, you must install `webpack-dev-server` as a devDepencency. Kindly do this
- [x] Kindly use ES6 arrow functions instead of the function keyword.

**Please make the above changes and ask for another review**

Feel free to leave a comment while mentioning me and I will be happy to reply.
### Happy Coding
_Slack: Oloo Moses_

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi @igorkol91, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Pull request merged**
